name: arisan
recipe: laravel
config:
  via: nginx:1.18
  cache: redis
  composer_version: '2.1.12'
  webroot: ./public
services:
  appserver:
    type: php:8.1
  database:
    type: mysql:5.7
    portforward: true
    creds:
      user: arisan
      password: arisan
      database: arisan
  phpmyadmin:
    type: phpmyadmin:5.0
  mailhog:
    type: mailhog
tooling:
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
    